// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: taskd/v1/runner.proto

package taskdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunRequest carries the task identity and its params as a JSON object.
type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RefId         string                 `protobuf:"bytes,2,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_taskd_v1_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskd_v1_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_taskd_v1_runner_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RunRequest) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *RunRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

// RunResponse is intentionally empty for now; fields can be added later.
type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_taskd_v1_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskd_v1_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_taskd_v1_runner_proto_rawDescGZIP(), []int{1}
}

var File_taskd_v1_runner_proto protoreflect.FileDescriptor

const file_taskd_v1_runner_proto_rawDesc = "" +
	"\n" +
	"\x15taskd/v1/runner.proto\x12\btaskd.v1\x1a\x1cgoogle/protobuf/struct.proto\"m\n" +
	"\n" +
	"RunRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06ref_id\x18\x02 \x01(\tR\x05refId\x12/\n" +
	"\x06params\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06params\"\r\n" +
	"\vRunResponse2<\n" +
	"\x06Runner\x122\n" +
	"\x03Run\x12\x14.taskd.v1.RunRequest\x1a\x15.taskd.v1.RunResponseB6Z4github.com/flametest/taskd/pkg/proto/taskdv1;taskdv1b\x06proto3"

var (
	file_taskd_v1_runner_proto_rawDescOnce sync.Once
	file_taskd_v1_runner_proto_rawDescData []byte
)

func file_taskd_v1_runner_proto_rawDescGZIP() []byte {
	file_taskd_v1_runner_proto_rawDescOnce.Do(func() {
		file_taskd_v1_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskd_v1_runner_proto_rawDesc), len(file_taskd_v1_runner_proto_rawDesc)))
	})
	return file_taskd_v1_runner_proto_rawDescData
}

var file_taskd_v1_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_taskd_v1_runner_proto_goTypes = []any{
	(*RunRequest)(nil),      // 0: taskd.v1.RunRequest
	(*RunResponse)(nil),     // 1: taskd.v1.RunResponse
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_taskd_v1_runner_proto_depIdxs = []int32{
	2, // 0: taskd.v1.RunRequest.params:type_name -> google.protobuf.Struct
	0, // 1: taskd.v1.Runner.Run:input_type -> taskd.v1.RunRequest
	1, // 2: taskd.v1.Runner.Run:output_type -> taskd.v1.RunResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_taskd_v1_runner_proto_init() }
func file_taskd_v1_runner_proto_init() {
	if File_taskd_v1_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskd_v1_runner_proto_rawDesc), len(file_taskd_v1_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taskd_v1_runner_proto_goTypes,
		DependencyIndexes: file_taskd_v1_runner_proto_depIdxs,
		MessageInfos:      file_taskd_v1_runner_proto_msgTypes,
	}.Build()
	File_taskd_v1_runner_proto = out.File
	file_taskd_v1_runner_proto_goTypes = nil
	file_taskd_v1_runner_proto_depIdxs = nil
}
